# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ClassifyDialogUi.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ClassifyDialog(object):
    def setupUi(self, ClassifyDialog):
        ClassifyDialog.setObjectName("ClassifyDialog")
        ClassifyDialog.setWindowModality(QtCore.Qt.NonModal)
        ClassifyDialog.resize(655, 742)
        ClassifyDialog.setSizeGripEnabled(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(ClassifyDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea_2 = QtWidgets.QScrollArea(ClassifyDialog)
        self.scrollArea_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 629, 637))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox_2 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName("gridLayout")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.uSourceLayer = gui.QgsMapLayerComboBox(self.groupBox_2)
        self.uSourceLayer.setObjectName("uSourceLayer")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.uSourceLayer)
        self.gridLayout.addLayout(self.formLayout_2, 1, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.groupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
<<<<<<< HEAD
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.uBoth = QtWidgets.QRadioButton(self.groupBox)
        self.uBoth.setObjectName("uBoth")
        self.horizontalLayout_7.addWidget(self.uBoth)
        self.uLayerClassifys = QtWidgets.QRadioButton(self.groupBox)
        self.uLayerClassifys.setObjectName("uLayerClassifys")
        self.horizontalLayout_7.addWidget(self.uLayerClassifys)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.gridLayout_2.addLayout(self.horizontalLayout_7, 0, 0, 1, 3)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 10, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 5, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 3, 0, 1, 1)
        self.uNClassify = QtWidgets.QSpinBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uNClassify.sizePolicy().hasHeightForWidth())
        self.uNClassify.setSizePolicy(sizePolicy)
        self.uNClassify.setMinimum(1)
        self.uNClassify.setMaximum(9999)
        self.uNClassify.setProperty("value", 10)
        self.uNClassify.setObjectName("uNClassify")
        self.gridLayout_2.addWidget(self.uNClassify, 3, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 8, 0, 1, 1)
        self.uExtend = QtWidgets.QComboBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uExtend.sizePolicy().hasHeightForWidth())
        self.uExtend.setSizePolicy(sizePolicy)
        self.uExtend.setObjectName("uExtend")
        self.gridLayout_2.addWidget(self.uExtend, 8, 1, 1, 1)
=======
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 4, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 0, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.groupBox)
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 1, 0, 1, 1)
>>>>>>> More dialog tweaks
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.uSetMaximum = QtWidgets.QCheckBox(self.groupBox)
        self.uSetMaximum.setObjectName("uSetMaximum")
        self.horizontalLayout_6.addWidget(self.uSetMaximum)
        self.uMaxClassify = QtWidgets.QDoubleSpinBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uMaxClassify.sizePolicy().hasHeightForWidth())
        self.uMaxClassify.setSizePolicy(sizePolicy)
        self.uMaxClassify.setLocale(QtCore.QLocale(QtCore.QLocale.C, QtCore.QLocale.AnyCountry))
        self.uMaxClassify.setDecimals(4)
        self.uMaxClassify.setMinimum(-999999999.0)
        self.uMaxClassify.setMaximum(999999999.0)
        self.uMaxClassify.setObjectName("uMaxClassify")
        self.horizontalLayout_6.addWidget(self.uMaxClassify)
        self.gridLayout_2.addLayout(self.horizontalLayout_6, 4, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 5, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 6, 1, 1, 1)
        self.uNClassify = QtWidgets.QSpinBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uNClassify.sizePolicy().hasHeightForWidth())
        self.uNClassify.setSizePolicy(sizePolicy)
        self.uNClassify.setMinimum(1)
        self.uNClassify.setMaximum(9999)
        self.uNClassify.setProperty("value", 10)
        self.uNClassify.setObjectName("uNClassify")
        self.gridLayout_2.addWidget(self.uNClassify, 2, 1, 1, 1)
        self.uMethod = QtWidgets.QComboBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uMethod.sizePolicy().hasHeightForWidth())
        self.uMethod.setSizePolicy(sizePolicy)
        self.uMethod.setObjectName("uMethod")
        self.gridLayout_2.addWidget(self.uMethod, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 3, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 2, 0, 1, 1)
        self.uClassifyInterval = QtWidgets.QDoubleSpinBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uClassifyInterval.sizePolicy().hasHeightForWidth())
        self.uClassifyInterval.setSizePolicy(sizePolicy)
        self.uClassifyInterval.setLocale(QtCore.QLocale(QtCore.QLocale.C, QtCore.QLocale.AnyCountry))
        self.uClassifyInterval.setDecimals(4)
        self.uClassifyInterval.setMinimum(-999999999.0)
        self.uClassifyInterval.setMaximum(999999999.0)
        self.uClassifyInterval.setObjectName("uClassifyInterval")
        self.gridLayout_2.addWidget(self.uClassifyInterval, 1, 1, 1, 1)
        self.uExtend = QtWidgets.QComboBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uExtend.sizePolicy().hasHeightForWidth())
        self.uExtend.setSizePolicy(sizePolicy)
        self.uExtend.setObjectName("uExtend")
        self.gridLayout_2.addWidget(self.uExtend, 5, 1, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_5.setSpacing(10)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.uSetMinimum = QtWidgets.QCheckBox(self.groupBox)
        self.uSetMinimum.setObjectName("uSetMinimum")
        self.horizontalLayout_5.addWidget(self.uSetMinimum)
        self.uMinClassify = QtWidgets.QDoubleSpinBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uMinClassify.sizePolicy().hasHeightForWidth())
        self.uMinClassify.setSizePolicy(sizePolicy)
        self.uMinClassify.setLocale(QtCore.QLocale(QtCore.QLocale.C, QtCore.QLocale.AnyCountry))
        self.uMinClassify.setDecimals(4)
        self.uMinClassify.setMinimum(-999999999.0)
        self.uMinClassify.setMaximum(999999999.0)
        self.uMinClassify.setObjectName("uMinClassify")
        self.horizontalLayout_5.addWidget(self.uMinClassify)
        self.gridLayout_2.addLayout(self.horizontalLayout_5, 3, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.groupBox_3 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setContentsMargins(-1, -1, -1, 6)
        self.formLayout.setObjectName("formLayout")
        self.label_8 = QtWidgets.QLabel(self.groupBox_3)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.uOutputName = QtWidgets.QLineEdit(self.groupBox_3)
        self.uOutputName.setObjectName("uOutputName")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.uOutputName)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(0, 0, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.uPrecision = QtWidgets.QSpinBox(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uPrecision.sizePolicy().hasHeightForWidth())
        self.uPrecision.setSizePolicy(sizePolicy)
        self.uPrecision.setMinimum(-1)
        self.uPrecision.setMaximum(10)
        self.uPrecision.setProperty("value", 4)
        self.uPrecision.setObjectName("uPrecision")
        self.horizontalLayout_2.addWidget(self.uPrecision)
        self.label_14 = QtWidgets.QLabel(self.groupBox_3)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_2.addWidget(self.label_14)
        self.uTrimZeros = QtWidgets.QCheckBox(self.groupBox_3)
        self.uTrimZeros.setText("")
        self.uTrimZeros.setObjectName("uTrimZeros")
        self.horizontalLayout_2.addWidget(self.uTrimZeros)
        self.label_12 = QtWidgets.QLabel(self.groupBox_3)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_2.addWidget(self.label_12)
        self.uLabelUnits = QtWidgets.QLineEdit(self.groupBox_3)
        self.uLabelUnits.setObjectName("uLabelUnits")
        self.horizontalLayout_2.addWidget(self.uLabelUnits)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.label_9 = QtWidgets.QLabel(self.groupBox_3)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.uApplyColors = QtWidgets.QCheckBox(self.groupBox_3)
        self.uApplyColors.setText("")
        self.uApplyColors.setObjectName("uApplyColors")
        self.horizontalLayout_4.addWidget(self.uApplyColors)
        self.uColorRamp = gui.QgsColorRampButton(self.groupBox_3)
        self.uColorRamp.setObjectName("uColorRamp")
        self.horizontalLayout_4.addWidget(self.uColorRamp)
        self.uReverseRamp = QtWidgets.QCheckBox(self.groupBox_3)
        self.uReverseRamp.setObjectName("uReverseRamp")
        self.horizontalLayout_4.addWidget(self.uReverseRamp)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.horizontalLayout_4.setStretch(1, 1)
        self.formLayout.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_4)
        self.label_13 = QtWidgets.QLabel(self.groupBox_3)
        self.label_13.setObjectName("label_13")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.gridLayout_4.addLayout(self.formLayout, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout.addWidget(self.scrollArea_2)
        self.uMessageBar = gui.QgsMessageBar(ClassifyDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uMessageBar.sizePolicy().hasHeightForWidth())
        self.uMessageBar.setSizePolicy(sizePolicy)
        self.uMessageBar.setMinimumSize(QtCore.QSize(0, 27))
        self.uMessageBar.setObjectName("uMessageBar")
        self.verticalLayout.addWidget(self.uMessageBar)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.progressBar = QtWidgets.QProgressBar(ClassifyDialog)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar.setTextVisible(True)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_8.addWidget(self.progressBar)
        self.uAddButton = QtWidgets.QPushButton(ClassifyDialog)
        self.uAddButton.setObjectName("uAddButton")
        self.horizontalLayout_8.addWidget(self.uAddButton)
        self.uCloseButton = QtWidgets.QPushButton(ClassifyDialog)
        self.uCloseButton.setObjectName("uCloseButton")
        self.horizontalLayout_8.addWidget(self.uCloseButton)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.verticalLayout.setStretch(0, 1)
        self.label_3.setBuddy(self.uSourceLayer)
        self.label_6.setBuddy(self.uSetMaximum)
        self.label_7.setBuddy(self.uMethod)
        self.label_15.setBuddy(self.uClassifyInterval)
        self.label_10.setBuddy(self.uExtend)
        self.label_5.setBuddy(self.uSetMinimum)
        self.label.setBuddy(self.uNClassify)
        self.label_8.setBuddy(self.uOutputName)
        self.label_14.setBuddy(self.uTrimZeros)
        self.label_12.setBuddy(self.uLabelUnits)
        self.label_9.setBuddy(self.uPrecision)
        self.label_13.setBuddy(self.uApplyColors)

        self.retranslateUi(ClassifyDialog)
        QtCore.QMetaObject.connectSlotsByName(ClassifyDialog)
<<<<<<< HEAD
        ClassifyDialog.setTabOrder(self.uSourceLayer, self.uBoth)
        ClassifyDialog.setTabOrder(self.uBoth, self.uLayerClassifys)
        ClassifyDialog.setTabOrder(self.uLayerClassifys, self.uMethod)
=======
        ClassifyDialog.setTabOrder(self.uSourceLayer, self.uMethod)
>>>>>>> More dialog tweaks
        ClassifyDialog.setTabOrder(self.uMethod, self.uClassifyInterval)
        ClassifyDialog.setTabOrder(self.uClassifyInterval, self.uNClassify)
        ClassifyDialog.setTabOrder(self.uNClassify, self.uSetMinimum)
        ClassifyDialog.setTabOrder(self.uSetMinimum, self.uMinClassify)
        ClassifyDialog.setTabOrder(self.uMinClassify, self.uSetMaximum)
        ClassifyDialog.setTabOrder(self.uSetMaximum, self.uMaxClassify)
        ClassifyDialog.setTabOrder(self.uMaxClassify, self.uExtend)
        ClassifyDialog.setTabOrder(self.uExtend, self.uOutputName)
        ClassifyDialog.setTabOrder(self.uOutputName, self.uPrecision)
        ClassifyDialog.setTabOrder(self.uPrecision, self.uTrimZeros)
        ClassifyDialog.setTabOrder(self.uTrimZeros, self.uLabelUnits)
        ClassifyDialog.setTabOrder(self.uLabelUnits, self.uApplyColors)
        ClassifyDialog.setTabOrder(self.uApplyColors, self.uColorRamp)
        ClassifyDialog.setTabOrder(self.uColorRamp, self.uReverseRamp)
        ClassifyDialog.setTabOrder(self.uReverseRamp, self.uAddButton)
        ClassifyDialog.setTabOrder(self.uAddButton, self.uCloseButton)

    def retranslateUi(self, ClassifyDialog):
        _translate = QtCore.QCoreApplication.translate
        ClassifyDialog.setWindowTitle(_translate("ClassifyDialog", "Classify"))
        self.groupBox_2.setTitle(_translate("ClassifyDialog", "Input"))
        self.label_3.setText(_translate("ClassifyDialog", "Raster layer"))
        self.groupBox.setTitle(_translate("ClassifyDialog", "Settings"))
<<<<<<< HEAD
        self.uBoth.setText(_translate("ClassifyDialog", "both"))
        self.uLayerClassifys.setText(_translate("ClassifyDialog", "Classify layers"))
=======
        self.label_6.setText(_translate("ClassifyDialog", "Maximum"))
        self.label_7.setText(_translate("ClassifyDialog", "Method"))
        self.label_15.setText(_translate("ClassifyDialog", "Interval"))
        self.uSetMaximum.setText(_translate("ClassifyDialog", "Set"))
        self.label_10.setText(_translate("ClassifyDialog", "Extend"))
        self.uNClassify.setStatusTip(_translate("ClassifyDialog", "Number of levels between min and max value (from data field)"))
>>>>>>> More dialog tweaks
        self.label_5.setText(_translate("ClassifyDialog", "Minimum"))
        self.label.setText(_translate("ClassifyDialog", "Number"))
        self.uSetMinimum.setText(_translate("ClassifyDialog", "Set"))
        self.groupBox_3.setTitle(_translate("ClassifyDialog", "Output"))
        self.label_8.setText(_translate("ClassifyDialog", "Layer name"))
        self.uPrecision.setStatusTip(_translate("ClassifyDialog", "Number of decimal places shown in labels"))
        self.label_14.setText(_translate("ClassifyDialog", "Trim zeros"))
        self.label_12.setText(_translate("ClassifyDialog", "Units"))
        self.label_9.setText(_translate("ClassifyDialog", "Label precision"))
        self.uReverseRamp.setText(_translate("ClassifyDialog", "reverse"))
        self.label_13.setText(_translate("ClassifyDialog", "Apply colours"))
        self.uAddButton.setText(_translate("ClassifyDialog", "Add"))
        self.uCloseButton.setText(_translate("ClassifyDialog", "Close"))


from qgis import gui


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ClassifyDialog = QtWidgets.QDialog()
    ui = Ui_ClassifyDialog()
    ui.setupUi(ClassifyDialog)
    ClassifyDialog.show()
    sys.exit(app.exec_())
